<?php
/**
 * K-Load v2 (https://demo.maddela.org/k-load/).
 *
 * @link      https://www.maddela.org
 * @link      https://github.com/kanalumaddela/k-load-v2
 *
 * @author    kanalumaddela <git@maddela.org>
 * @copyright Copyright (c) 2018-2020 Maddela
 * @license   MIT
 */

namespace K_Load;

use Adbar\Dot;

class DotArray extends Dot
{
//    public function get($key = null, $default = null, $returnByRef = false)
//    {
//        if (is_null($key)) {
//            return $this->items;
//        }
//
//        if ($this->exists($this->items, $key)) {
//            return $this->items[$key];
//        }
//
//        if (strpos($key, '.') === false) {
//            return $default;
//        }
//
//        $items = $this->items;
//
//        foreach (explode('.', $key) as $segment) {
//            if (!is_array($items) || !$this->exists($items, $segment)) {
//                return $default;
//            }
//
//            $items = &$items[$segment];
//        }
//
//        return $items;
//
//        return parent::get($key, $default); // TODO: Change the autogenerated stub
//    }
}