<?php
/*
 * K-Load v2 (https://demo.maddela.org/k-load/).
 *
 * @link      https://www.maddela.org
 * @link      https://github.com/kanalumaddela/k-load-v2
 *
 * @author    kanalumaddela <git@maddela.org>
 * @copyright Copyright (c) 2018-2021 kanalumaddela
 * @license   MIT
 */

namespace KLoad;

use stdClass;

class SteamLogin extends \kanalumaddela\SteamLogin\SteamLogin
{
    protected static bool $forceInvalid = false;

    public static function validRequest(): bool
    {
        if (static::$forceInvalid) {
            return false;
        }

        return parent::validRequest(); // TODO: Change the autogenerated stub
    }

    protected function validate(): bool
    {
        if (static::$forceInvalid) {
            return false;
        }

        return parent::validate(); // TODO: Change the autogenerated stub
    }

    public function getUserInfo($steamid): stdClass
    {
        return $this->userInfo($steamid);
    }
}
